import { CardOrdemTransporte } from "#/components/card/cardOrdemTransporte";
import { Button } from "#/components/ui/button";
import { Field } from "#/components/ui/field";
import { Input } from "#/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "#/components/ui/select";
import { createFileRoute } from "@tanstack/react-router";
import { Plus, Search, Truck } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/_authenticated/ordemDeTransporte")({
  component: RouteComponent,
});

function RouteComponent() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedStatus, setSelectedStatus] = useState("todos");

const ordemDeTransporte = [
  {
    id: 1,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10001",
    status: "trânsito",
    emissao: "2026-04-26 08:15:22.000Z",
    numerocontainer: "MAEU1829304",
    container: "Dry 40'",
    notaFiscal: "102938",
    motorista: "Carlos Eduardo Silva",
    caminhao: "Volvo FH 540",
    placa: "BRA2E19",
    partida: "Santos - SP",
    destino: "Campinas - SP",
  },
  {
    id: 2,
    responsavel: "Mariana Souza",
    ordemDeTransporte: "OT-10002",
    status: "entregue",
    emissao: "2025-11-14 14:30:10.000Z",
    numerocontainer: "MSCU9281745",
    container: "Reefer 40'",
    notaFiscal: "102939",
    motorista: "Roberto Alves",
    caminhao: "Scania R450",
    placa: "ABC1D23",
    partida: "Paranaguá - PR",
    destino: "Curitiba - PR",
  },
  {
    id: 3,
    responsavel: "Lucas Ferreira",
    ordemDeTransporte: "OT-10003",
    status: "coleta",
    emissao: "2026-01-10 10:00:00.000Z",
    numerocontainer: "CMAU7362514",
    container: "Dry 20'",
    notaFiscal: "102940",
    motorista: "Fernando Souza",
    caminhao: "Mercedes-Benz Actros",
    placa: "KXZ9F88",
    partida: "Guarujá - SP",
    destino: "Sertãozinho - SP",
  },
  {
    id: 4,
    responsavel: "Camila Rocha",
    ordemDeTransporte: "OT-10004",
    status: "ocorrência",
    emissao: "2024-08-19 18:22:45.000Z",
    numerocontainer: "COSU8473625",
    container: "Open Top",
    notaFiscal: "102941",
    motorista: "Luciano Mendes",
    caminhao: "DAF XF 530",
    placa: "MNO4H56",
    partida: "Itajaí - SC",
    destino: "Blumenau - SC",
  },
  {
    id: 5,
    responsavel: "Rafael Barbosa",
    ordemDeTransporte: "OT-10005",
    status: "trânsito",
    emissao: "2026-03-02 06:45:12.000Z",
    numerocontainer: "HAPU9182736",
    container: "Dry 40'",
    notaFiscal: "102942",
    motorista: "Marcos Ribeiro",
    caminhao: "MAN TGX 28.440",
    placa: "GHI7J89",
    partida: "Rio Grande - RS",
    destino: "Caxias do Sul - RS",
  },
  {
    id: 6,
    responsavel: "Beatriz Lima",
    ordemDeTransporte: "OT-10006",
    status: "entregue",
    emissao: "2025-05-12 11:10:05.000Z",
    numerocontainer: "EGLU1298347",
    container: "Flat Rack",
    notaFiscal: "102943",
    motorista: "Ailton Pereira",
    caminhao: "Iveco Hi-Way",
    placa: "QWE3R45",
    partida: "Suape - PE",
    destino: "Recife - PE",
  },
  {
    id: 7,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10007",
    status: "coleta",
    emissao: "2026-02-28 09:30:18.000Z",
    numerocontainer: "OOCU9834712",
    container: "Reefer 20'",
    notaFiscal: "102944",
    motorista: "Thiago Barbosa",
    caminhao: "Volkswagen Meteor",
    placa: "ZXC9V87",
    partida: "Cubatão - SP",
    destino: "São José dos Campos - SP",
  },
  {
    id: 8,
    responsavel: "Gabriel Santos",
    ordemDeTransporte: "OT-10008",
    status: "trânsito",
    emissao: "2024-12-05 22:15:30.000Z",
    numerocontainer: "SUDU8273641",
    container: "Dry 40'",
    notaFiscal: "102945",
    motorista: "Marcio Santos",
    caminhao: "Volvo FH 460",
    placa: "TYU5I67",
    partida: "Pecém - CE",
    destino: "Fortaleza - CE",
  },
  {
    id: 9,
    responsavel: "Juliana Martins",
    ordemDeTransporte: "OT-10009",
    status: "entregue",
    emissao: "2025-09-30 16:50:00.000Z",
    numerocontainer: "ONEU3847261",
    container: "Dry 20'",
    notaFiscal: "102946",
    motorista: "André Luiz Castro",
    caminhao: "Scania R500",
    placa: "OPL2M34",
    partida: "Santos - SP",
    destino: "Belo Horizonte - MG",
  },
  {
    id: 10,
    responsavel: "Thiago Oliveira",
    ordemDeTransporte: "OT-10010",
    status: "ocorrência",
    emissao: "2026-05-18 01:05:40.000Z",
    numerocontainer: "YMLU8374625",
    container: "Reefer 40'",
    notaFiscal: "102947",
    motorista: "Gilberto Rocha",
    caminhao: "Mercedes-Benz Axor",
    placa: "RTY8U90",
    partida: "Rio de Janeiro - RJ",
    destino: "Volta Redonda - RJ",
  },
  {
    id: 11,
    responsavel: "Fernanda Costa",
    ordemDeTransporte: "OT-10011",
    status: "trânsito",
    emissao: "2025-03-22 05:12:00.000Z",
    numerocontainer: "EVER4738291",
    container: "Dry 40'",
    notaFiscal: "102948",
    motorista: "Rodrigo Costa",
    caminhao: "Volvo FH 540",
    placa: "JHG4F32",
    partida: "Vitoria - ES",
    destino: "Cachoeiro de Itapemirim - ES",
  },
  {
    id: 12,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10012",
    status: "coleta",
    emissao: "2024-10-11 11:40:00.000Z",
    numerocontainer: "ZIMU9283746",
    container: "Dry 20'",
    notaFiscal: "102949",
    motorista: "Edson Martins",
    caminhao: "Scania G450",
    placa: "MNB6V54",
    partida: "São Francisco do Sul - SC",
    destino: "Joinville - SC",
  },
  {
    id: 13,
    responsavel: "Patricia Mendes",
    ordemDeTransporte: "OT-10013",
    status: "entregue",
    emissao: "2025-07-04 09:15:00.000Z",
    numerocontainer: "UACU8374920",
    container: "Dry 40'",
    notaFiscal: "102950",
    motorista: "Paulo Henrique",
    caminhao: "DAF XF 480",
    placa: "POI9U87",
    partida: "Santos - SP",
    destino: "Goiânia - GO",
  },
  {
    id: 14,
    responsavel: "Rodrigo Alves",
    ordemDeTransporte: "OT-10014",
    status: "trânsito",
    emissao: "2026-06-15 19:30:00.000Z",
    numerocontainer: "KMTC7281934",
    container: "Reefer 40'",
    notaFiscal: "102951",
    motorista: "Sérgio Ramos",
    caminhao: "Volkswagen Constellation",
    placa: "LKJ5H43",
    partida: "Manaus - AM",
    destino: "Boa Vista - RR",
  },
  {
    id: 15,
    responsavel: "Vanessa Cardoso",
    ordemDeTransporte: "OT-10015",
    status: "coleta",
    emissao: "2025-01-20 07:20:11.000Z",
    numerocontainer: "WHLU9382710",
    container: "Dry 20'",
    notaFiscal: "102952",
    motorista: "Lucas Lima",
    caminhao: "Mercedes-Benz Atego",
    placa: "QAZ1WS2",
    partida: "Salvador - BA",
    destino: "Feira de Santana - BA",
  },
  {
    id: 16,
    responsavel: "Diego Ribeiro",
    ordemDeTransporte: "OT-10016",
    status: "entregue",
    emissao: "2024-06-08 13:00:00.000Z",
    numerocontainer: "SITC8273940",
    container: "Dry 40'",
    notaFiscal: "102953",
    motorista: "Renato Teixeira",
    caminhao: "Volvo FM 380",
    placa: "EDC3RF4",
    partida: "Santos - SP",
    destino: "Jundiaí - SP",
  },
  {
    id: 17,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10017",
    status: "trânsito",
    emissao: "2026-02-14 03:50:00.000Z",
    numerocontainer: "TSLU9182374",
    container: "Open Top",
    notaFiscal: "102954",
    motorista: "Fábio Junior",
    caminhao: "Scania R450",
    placa: "TGB5YH6",
    partida: "Paranaguá - PR",
    destino: "Maringá - PR",
  },
  {
    id: 18,
    responsavel: "Aline Carvalho",
    ordemDeTransporte: "OT-10018",
    status: "ocorrência",
    emissao: "2025-10-02 17:10:00.000Z",
    numerocontainer: "SMLU7364521",
    container: "Flat Rack",
    notaFiscal: "102955",
    motorista: "Wagner Moreira",
    caminhao: "Iveco Stralis",
    placa: "UJM7IK8",
    partida: "Rio Grande - RS",
    destino: "Pelotas - RS",
  },
  {
    id: 19,
    responsavel: "Marcelo Fonseca",
    ordemDeTransporte: "OT-10019",
    status: "coleta",
    emissao: "2024-11-27 12:00:00.000Z",
    numerocontainer: "IRSU9283741",
    container: "Dry 20'",
    notaFiscal: "102956",
    motorista: "Daniel Farias",
    caminhao: "MAN TGX 29.480",
    placa: "OLP9IK8",
    partida: "Santos - SP",
    destino: "Sorocaba - SP",
  },
  {
    id: 20,
    responsavel: "Renata Vasconcelos",
    ordemDeTransporte: "OT-10020",
    status: "trânsito",
    emissao: "2026-07-01 02:10:00.000Z",
    numerocontainer: "MATS8273645",
    container: "Reefer 40'",
    notaFiscal: "102957",
    motorista: "Claudio Duarte",
    caminhao: "Volvo FH 500",
    placa: "RFV4TGB",
    partida: "Itajaí - SC",
    destino: "Chapecó - SC",
  },
  {
    id: 21,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10021",
    status: "entregue",
    emissao: "2025-02-18 15:40:00.000Z",
    numerocontainer: "TLLU9384726",
    container: "Dry 40'",
    notaFiscal: "102958",
    motorista: "Jorge Luiz",
    caminhao: "Mercedes-Benz Actros",
    placa: "YHN6UJM",
    partida: "Vitoria - ES",
    destino: "Belo Horizonte - MG",
  },
  {
    id: 22,
    responsavel: "Felipe Andrade",
    ordemDeTransporte: "OT-10022",
    status: "trânsito",
    emissao: "2024-09-12 21:00:00.000Z",
    numerocontainer: "HAMU8273619",
    container: "Dry 20'",
    notaFiscal: "102959",
    motorista: "Vitor Hugo",
    caminhao: "Scania P360",
    placa: "EDC4RFV",
    partida: "Suape - PE",
    destino: "Caruaru - PE",
  },
  {
    id: 23,
    responsavel: "Larissa Dias",
    ordemDeTransporte: "OT-10023",
    status: "coleta",
    emissao: "2026-03-19 08:00:00.000Z",
    numerocontainer: "CULU9382716",
    container: "Reefer 20'",
    notaFiscal: "102960",
    motorista: "Leandro Nogueira",
    caminhao: "Volkswagen Meteor",
    placa: "WSX3EDC",
    partida: "Guarujá - SP",
    destino: "Ribeirão Preto - SP",
  },
  {
    id: 24,
    responsavel: "Bruno Nogueira",
    ordemDeTransporte: "OT-10024",
    status: "entregue",
    emissao: "2025-08-05 08:30:00.000Z",
    numerocontainer: "CNIU8273640",
    container: "Dry 40'",
    notaFiscal: "102961",
    motorista: "Bruno Machado",
    caminhao: "DAF XF 530",
    placa: "QAZ2WSX",
    partida: "Santos - SP",
    destino: "Uberlândia - MG",
  },
  {
    id: 25,
    responsavel: "Sofia Prado",
    ordemDeTransporte: "OT-10025",
    status: "ocorrência",
    emissao: "2024-07-23 04:15:00.000Z",
    numerocontainer: "CSQU7362519",
    container: "Open Top",
    notaFiscal: "102962",
    motorista: "Alexandre Pires",
    caminhao: "Volvo FH 460",
    placa: "PLM0OKN",
    partida: "Rio de Janeiro - RJ",
    destino: "Macaé - RJ",
  },
  {
    id: 26,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10026",
    status: "trânsito",
    emissao: "2026-05-30 13:20:00.000Z",
    numerocontainer: "IALU8273641",
    container: "Dry 40'",
    notaFiscal: "102963",
    motorista: "Gabriel Jesus",
    caminhao: "Scania R540",
    placa: "OKN9IJB",
    partida: "Paranaguá - PR",
    destino: "Londrina - PR",
  },
  {
    id: 27,
    responsavel: "Mariana Souza",
    ordemDeTransporte: "OT-10027",
    status: "coleta",
    emissao: "2025-04-17 10:45:00.000Z",
    numerocontainer: "MOHU8273642",
    container: "Dry 20'",
    notaFiscal: "102964",
    motorista: "Rafael Santos",
    caminhao: "Mercedes-Benz Atego",
    placa: "IJB8UHV",
    partida: "Santos - SP",
    destino: "Bauru - SP",
  },
  {
    id: 28,
    responsavel: "Lucas Ferreira",
    ordemDeTransporte: "OT-10028",
    status: "entregue",
    emissao: "2024-12-19 17:00:00.000Z",
    numerocontainer: "SINU9283741",
    container: "Reefer 40'",
    notaFiscal: "102965",
    motorista: "Diego Nunes",
    caminhao: "MAN TGX 28.440",
    placa: "UHV7YGC",
    partida: "Itajaí - SC",
    destino: "Florianópolis - SC",
  },
  {
    id: 29,
    responsavel: "Camila Rocha",
    ordemDeTransporte: "OT-10029",
    status: "trânsito",
    emissao: "2026-01-08 00:30:00.000Z",
    numerocontainer: "SASU8273610",
    container: "Dry 40'",
    notaFiscal: "102966",
    motorista: "Samuel Rosa",
    caminhao: "Iveco Hi-Way",
    placa: "YGC6XFZ",
    partida: "Rio Grande - RS",
    destino: "Porto Alegre - RS",
  },
  {
    id: 30,
    responsavel: "Rafael Barbosa",
    ordemDeTransporte: "OT-10030",
    status: "coleta",
    emissao: "2025-06-25 09:00:00.000Z",
    numerocontainer: "HEID8273640",
    container: "Flat Rack",
    notaFiscal: "102967",
    motorista: "Gustavo Lima",
    caminhao: "Volvo FH 540",
    placa: "XFZ5TSR",
    partida: "Santos - SP",
    destino: "Taubaté - SP",
  },
  {
    id: 31,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10031",
    status: "entregue",
    emissao: "2024-05-14 10:20:00.000Z",
    numerocontainer: "GSLU9283710",
    container: "Dry 20'",
    notaFiscal: "102968",
    motorista: "Vinicius Junior",
    caminhao: "Volkswagen Constellation",
    placa: "TSR4EDC",
    partida: "Pecém - CE",
    destino: "Sobral - CE",
  },
  {
    id: 32,
    responsavel: "Beatriz Lima",
    ordemDeTransporte: "OT-10032",
    status: "trânsito",
    emissao: "2026-04-03 18:00:00.000Z",
    numerocontainer: "CKLU8273619",
    container: "Reefer 40'",
    notaFiscal: "102969",
    motorista: "Matheus Henrique",
    caminhao: "Scania G440",
    placa: "EDC3RFV",
    partida: "Salvador - BA",
    destino: "Vitória da Conquista - BA",
  },
  {
    id: 33,
    responsavel: "Gabriel Santos",
    ordemDeTransporte: "OT-10033",
    status: "ocorrência",
    emissao: "2025-11-20 07:10:00.000Z",
    numerocontainer: "NVIU8273640",
    container: "Dry 40'",
    notaFiscal: "102970",
    motorista: "Thiago Silva",
    caminhao: "Mercedes-Benz Actros",
    placa: "RFV2TGB",
    partida: "Santos - SP",
    destino: "Piracicaba - SP",
  },
  {
    id: 34,
    responsavel: "Juliana Martins",
    ordemDeTransporte: "OT-10034",
    status: "coleta",
    emissao: "2024-08-01 11:15:00.000Z",
    numerocontainer: "BENU9283740",
    container: "Dry 20'",
    notaFiscal: "102971",
    motorista: "Igor Guimarães",
    caminhao: "DAF XF 480",
    placa: "TGB1YHN",
    partida: "Manaus - AM",
    destino: "Humaitá - AM",
  },
  {
    id: 35,
    responsavel: "Thiago Oliveira",
    ordemDeTransporte: "OT-10035",
    status: "entregue",
    emissao: "2026-02-09 14:00:00.000Z",
    numerocontainer: "LMCU8273610",
    container: "Open Top",
    notaFiscal: "102972",
    motorista: "Caio Castro",
    caminhao: "Volvo FM 370",
    placa: "YHN0UJM",
    partida: "Aratu - BA",
    destino: "Camaçari - BA",
  },
  {
    id: 36,
    responsavel: "Fernanda Costa",
    ordemDeTransporte: "OT-10036",
    status: "trânsito",
    emissao: "2025-01-29 15:45:00.000Z",
    numerocontainer: "DJLU9283740",
    container: "Dry 40'",
    notaFiscal: "102973",
    motorista: "Murilo Benício",
    caminhao: "Scania R450",
    placa: "UJM9IK8",
    partida: "Paranaguá - PR",
    destino: "Ponta Grossa - PR",
  },
  {
    id: 37,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10037",
    status: "coleta",
    emissao: "2024-10-05 08:30:00.000Z",
    numerocontainer: "SWLU8273619",
    container: "Reefer 20'",
    notaFiscal: "102974",
    motorista: "Otavio Mesquita",
    caminhao: "MAN TGX 29.440",
    placa: "IK87OLP",
    partida: "Santos - SP",
    destino: "Franca - SP",
  },
  {
    id: 38,
    responsavel: "Patricia Mendes",
    ordemDeTransporte: "OT-10038",
    status: "entregue",
    emissao: "2026-03-12 11:30:00.000Z",
    numerocontainer: "PASU9283710",
    container: "Dry 40'",
    notaFiscal: "102975",
    motorista: "Douglas Sampaio",
    caminhao: "Volkswagen Meteor",
    placa: "OLP6QAZ",
    partida: "Itajaí - SC",
    destino: "Criciúma - SC",
  },
  {
    id: 39,
    responsavel: "Rodrigo Alves",
    ordemDeTransporte: "OT-10039",
    status: "trânsito",
    emissao: "2025-09-08 01:20:00.000Z",
    numerocontainer: "STXU8273640",
    container: "Flat Rack",
    notaFiscal: "102976",
    motorista: "Elias Terceiro",
    caminhao: "Mercedes-Benz Axor",
    placa: "QAZ5WSX",
    partida: "Suape - PE",
    destino: "Petrolina - PE",
  },
  {
    id: 40,
    responsavel: "Vanessa Cardoso",
    ordemDeTransporte: "OT-10040",
    status: "ocorrência",
    emissao: "2024-04-18 20:10:00.000Z",
    numerocontainer: "RONG9283740",
    container: "Dry 20'",
    notaFiscal: "102977",
    motorista: "Felipe Titto",
    caminhao: "Iveco Hi-Way",
    placa: "WSX4EDC",
    partida: "Santos - SP",
    destino: "Presidente Prudente - SP",
  },
  {
    id: 41,
    responsavel: "Diego Ribeiro",
    ordemDeTransporte: "OT-10041",
    status: "coleta",
    emissao: "2026-06-22 10:10:00.000Z",
    numerocontainer: "TRHU8273610",
    container: "Dry 40'",
    notaFiscal: "102978",
    motorista: "Guilherme Winter",
    caminhao: "Volvo FH 540",
    placa: "EDC3RFV",
    partida: "Vitoria - ES",
    destino: "Linhares - ES",
  },
  {
    id: 42,
    responsavel: "Aline Carvalho",
    ordemDeTransporte: "OT-10042",
    status: "entregue",
    emissao: "2025-05-02 16:20:00.000Z",
    numerocontainer: "TGHU9283740",
    container: "Reefer 40'",
    notaFiscal: "102979",
    motorista: "Henrique Fogaça",
    caminhao: "Scania R500",
    placa: "RFV2TGB",
    partida: "Rio Grande - RS",
    destino: "Passo Fundo - RS",
  },
  {
    id: 43,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10043",
    status: "trânsito",
    emissao: "2024-11-09 04:00:00.000Z",
    numerocontainer: "MBLU8273619",
    container: "Dry 20'",
    notaFiscal: "102980",
    motorista: "Julio Rocha",
    caminhao: "DAF XF 530",
    placa: "TGB1YHN",
    partida: "Santos - SP",
    destino: "Marília - SP",
  },
  {
    id: 44,
    responsavel: "Marcelo Fonseca",
    ordemDeTransporte: "OT-10044",
    status: "coleta",
    emissao: "2026-02-01 06:15:00.000Z",
    numerocontainer: "BLJU9283740",
    container: "Open Top",
    notaFiscal: "102981",
    motorista: "Kleibson Souza",
    caminhao: "Mercedes-Benz Actros",
    placa: "YHN0UJM",
    partida: "Pecém - CE",
    destino: "Juazeiro do Norte - CE",
  },
  {
    id: 45,
    responsavel: "Renata Vasconcelos",
    ordemDeTransporte: "OT-10045",
    status: "entregue",
    emissao: "2025-03-15 18:30:00.000Z",
    numerocontainer: "SNCU8273610",
    container: "Dry 40'",
    notaFiscal: "102982",
    motorista: "Luan Santana",
    caminhao: "Volkswagen Constellation",
    placa: "UJM9IK8",
    partida: "Santos - SP",
    destino: "São José do Rio Preto - SP",
  },
  {
    id: 46,
    responsavel: "Felipe Andrade",
    ordemDeTransporte: "OT-10046",
    status: "trânsito",
    emissao: "2024-07-04 11:00:00.000Z",
    numerocontainer: "GESU9283740",
    container: "Reefer 20'",
    notaFiscal: "102983",
    motorista: "Michel Teló",
    caminhao: "Volvo FM 380",
    placa: "IK88OLP",
    partida: "Paranaguá - PR",
    destino: "Foz do Iguaçu - PR",
  },
  {
    id: 47,
    responsavel: "Larissa Dias",
    ordemDeTransporte: "OT-10047",
    status: "ocorrência",
    emissao: "2026-05-11 02:50:00.000Z",
    numerocontainer: "VMCU8273619",
    container: "Dry 40'",
    notaFiscal: "102984",
    motorista: "Neymar da Silva",
    caminhao: "Scania R450",
    placa: "OLP7QAZ",
    partida: "Rio de Janeiro - RJ",
    destino: "Resende - RJ",
  },
  {
    id: 48,
    responsavel: "Bruno Nogueira",
    ordemDeTransporte: "OT-10048",
    status: "coleta",
    emissao: "2025-12-01 11:50:00.000Z",
    numerocontainer: "LCLU9283740",
    container: "Flat Rack",
    notaFiscal: "102985",
    motorista: "Orlando Drummond",
    caminhao: "MAN TGX 28.440",
    placa: "QAZ6WSX",
    partida: "Itajaí - SC",
    destino: "Jaraguá do Sul - SC",
  },
  {
    id: 49,
    responsavel: "Sofia Prado",
    ordemDeTransporte: "OT-10049",
    status: "entregue",
    emissao: "2024-10-23 12:10:00.000Z",
    numerocontainer: "HDAS8273610",
    container: "Dry 20'",
    notaFiscal: "102986",
    motorista: "Pedro Bial",
    caminhao: "Iveco Stralis",
    placa: "WSX5EDC",
    partida: "Santos - SP",
    destino: "Limeira - SP",
  },
  {
    id: 50,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10050",
    status: "trânsito",
    emissao: "2026-04-10 03:15:00.000Z",
    numerocontainer: "KASD9283740",
    container: "Dry 40'",
    notaFiscal: "102987",
    motorista: "Quirino Neto",
    caminhao: "Mercedes-Benz Atego",
    placa: "EDC4RFV",
    partida: "Salvador - BA",
    destino: "Ilhéus - BA",
  },
  {
    id: 51,
    responsavel: "Mariana Souza",
    ordemDeTransporte: "OT-10051",
    status: "coleta",
    emissao: "2025-06-18 08:45:00.000Z",
    numerocontainer: "POIS8273619",
    container: "Reefer 40'",
    notaFiscal: "102988",
    motorista: "Ronaldo Nazario",
    caminhao: "Volvo FH 500",
    placa: "RFV3TGB",
    partida: "Santos - SP",
    destino: "Araraquara - SP",
  },
  {
    id: 52,
    responsavel: "Lucas Ferreira",
    ordemDeTransporte: "OT-10052",
    status: "entregue",
    emissao: "2024-09-02 09:00:00.000Z",
    numerocontainer: "LKJS9283740",
    container: "Dry 20'",
    notaFiscal: "102989",
    motorista: "Sidney Magal",
    caminhao: "Scania G450",
    placa: "TGB2YHN",
    partida: "Suape - PE",
    destino: "Olinda - PE",
  },
  {
    id: 53,
    responsavel: "Camila Rocha",
    ordemDeTransporte: "OT-10053",
    status: "trânsito",
    emissao: "2026-01-24 16:30:00.000Z",
    numerocontainer: "MNBV8273610",
    container: "Dry 40'",
    notaFiscal: "102990",
    motorista: "Tirullipa Junior",
    caminhao: "DAF XF 480",
    placa: "YHN1UJM",
    partida: "Manaus - AM",
    destino: "Itacoatiara - AM",
  },
  {
    id: 54,
    responsavel: "Rafael Barbosa",
    ordemDeTransporte: "OT-10054",
    status: "ocorrência",
    emissao: "2025-04-11 05:40:00.000Z",
    numerocontainer: "CXZA9283740",
    container: "Open Top",
    notaFiscal: "102991",
    motorista: "Ubirajara Silva",
    caminhao: "Volkswagen Meteor",
    placa: "UJM0IK8",
    partida: "Vitoria - ES",
    destino: "Colatina - ES",
  },
  {
    id: 55,
    responsavel: "Beatriz Lima",
    ordemDeTransporte: "OT-10055",
    status: "coleta",
    emissao: "2024-11-15 12:30:00.000Z",
    numerocontainer: "QWYE8273619",
    container: "Dry 20'",
    notaFiscal: "102992",
    motorista: "Valdir Braz",
    caminhao: "Mercedes-Benz Actros",
    placa: "IK89OLP",
    partida: "Guarujá - SP",
    destino: "Mogi das Cruzes - SP",
  },
  {
    id: 56,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10056",
    status: "entregue",
    emissao: "2026-03-29 18:00:00.000Z",
    numerocontainer: "IUYT9283740",
    container: "Reefer 20'",
    notaFiscal: "102993",
    motorista: "Wanderlei Silva",
    caminhao: "Volvo FH 460",
    placa: "OLP8QAZ",
    partida: "Rio Grande - RS",
    destino: "Santa Maria - RS",
  },
  {
    id: 57,
    responsavel: "Gabriel Santos",
    ordemDeTransporte: "OT-10057",
    status: "trânsito",
    emissao: "2025-07-22 02:00:00.000Z",
    numerocontainer: "OIKJ8273610",
    container: "Dry 40'",
    notaFiscal: "102994",
    motorista: "Xand Avião",
    caminhao: "Scania R540",
    placa: "QAZ7WSX",
    partida: "Santos - SP",
    destino: "Indaiatuba - SP",
  },
  {
    id: 58,
    responsavel: "Juliana Martins",
    ordemDeTransporte: "OT-10058",
    status: "coleta",
    emissao: "2024-06-30 07:50:00.000Z",
    numerocontainer: "YTRE9283740",
    container: "Flat Rack",
    notaFiscal: "102995",
    motorista: "Yudi Tamashiro",
    caminhao: "MAN TGX 29.480",
    placa: "WSX6EDC",
    partida: "Paranaguá - PR",
    destino: "Cascavel - PR",
  },
  {
    id: 59,
    responsavel: "Thiago Oliveira",
    ordemDeTransporte: "OT-10059",
    status: "entregue",
    emissao: "2026-05-04 10:15:00.000Z",
    numerocontainer: "RTEW8273619",
    container: "Dry 20'",
    notaFiscal: "102996",
    motorista: "Zico Arantes",
    caminhao: "Iveco Hi-Way",
    placa: "EDC5RFV",
    partida: "Itajaí - SC",
    destino: "Brusque - SC",
  },
  {
    id: 60,
    responsavel: "Fernanda Costa",
    ordemDeTransporte: "OT-10060",
    status: "trânsito",
    emissao: "2025-10-14 04:30:00.000Z",
    numerocontainer: "FDA28374019",
    container: "Reefer 40'",
    notaFiscal: "102997",
    motorista: "João Carlos",
    caminhao: "Volkswagen Meteor",
    placa: "ABC-1234",
    partida: "Santos - SP",
    destino: "Cubatão - SP",
  },
  {
    id: 61,
    responsavel: "Patricia Mendes",
    ordemDeTransporte: "OT-10061",
    status: "coleta",
    emissao: "2024-03-22 13:40:00.000Z",
    numerocontainer: "MAEU9988112",
    container: "Dry 40'",
    notaFiscal: "102998",
    motorista: "Jair Messias",
    caminhao: "Volvo FH 540",
    placa: "FGH8J99",
    partida: "Santos - SP",
    destino: "Atibaia - SP",
  },
  {
    id: 62,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10062",
    status: "entregue",
    emissao: "2026-02-17 08:25:00.000Z",
    numerocontainer: "MSCU1122334",
    container: "Dry 20'",
    notaFiscal: "102999",
    motorista: "Adilson Batista",
    caminhao: "Scania R450",
    placa: "JKL3M44",
    partida: "Paranaguá - PR",
    destino: "Punta Grossa - PR",
  },
  {
    id: 63,
    responsavel: "Rodrigo Alves",
    ordemDeTransporte: "OT-10063",
    status: "trânsito",
    emissao: "2025-08-11 19:10:00.000Z",
    numerocontainer: "CMAU4455667",
    container: "Reefer 40'",
    notaFiscal: "103000",
    motorista: "Bernardo Silva",
    caminhao: "Mercedes-Benz Actros",
    placa: "QWE5R66",
    partida: "Rio Grande - RS",
    destino: "Bento Gonçalves - RS",
  },
  {
    id: 64,
    responsavel: "Vanessa Cardoso",
    ordemDeTransporte: "OT-10064",
    status: "ocorrência",
    emissao: "2024-12-03 15:55:00.000Z",
    numerocontainer: "COSU7788990",
    container: "Open Top",
    notaFiscal: "103001",
    motorista: "Cássio Ramos",
    caminhao: "DAF XF 530",
    placa: "TYU7I88",
    partida: "Suape - PE",
    destino: "Jaboatão - PE",
  },
  {
    id: 65,
    responsavel: "Diego Ribeiro",
    ordemDeTransporte: "OT-10065",
    status: "coleta",
    emissao: "2026-06-02 09:35:00.000Z",
    numerocontainer: "HAPU2233445",
    container: "Flat Rack",
    notaFiscal: "103002",
    motorista: "Danilo Gentili",
    caminhao: "MAN TGX 28.440",
    placa: "OPL9M00",
    partida: "Itajaí - SC",
    destino: "Lages - SC",
  },
  {
    id: 66,
    responsavel: "Aline Carvalho",
    ordemDeTransporte: "OT-10066",
    status: "entregue",
    emissao: "2025-01-19 22:05:00.000Z",
    numerocontainer: "EGLU5566778",
    container: "Dry 40'",
    notaFiscal: "103003",
    motorista: "Everton Ribeiro",
    caminhao: "Iveco Hi-Way",
    placa: "ZXC2V33",
    partida: "Vitoria - ES",
    destino: "Vila Velha - ES",
  },
  {
    id: 67,
    responsavel: "Marcelo Fonseca",
    ordemDeTransporte: "OT-10067",
    status: "trânsito",
    emissao: "2024-05-28 11:20:00.000Z",
    numerocontainer: "OOCU8899001",
    container: "Dry 20'",
    notaFiscal: "103004",
    motorista: "Fabiano Oliveira",
    caminhao: "Volkswagen Meteor",
    placa: "ASD4F55",
    partida: "Santos - SP",
    destino: "Barueri - SP",
  },
  {
    id: 68,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10068",
    status: "coleta",
    emissao: "2026-03-05 07:15:00.000Z",
    numerocontainer: "SUDU1133557",
    container: "Reefer 20'",
    notaFiscal: "103005",
    motorista: "Gerson Canhota",
    caminhao: "Volvo FH 460",
    placa: "GHJ6K77",
    partida: "Salvador - BA",
    destino: "Jequié - BA",
  },
  {
    id: 69,
    responsavel: "Renata Vasconcelos",
    ordemDeTransporte: "OT-10069",
    status: "entregue",
    emissao: "2025-11-08 17:45:00.000Z",
    numerocontainer: "ONEU9977553",
    container: "Dry 40'",
    notaFiscal: "103006",
    motorista: "Hélio dos Anjos",
    caminhao: "Scania R500",
    placa: "BNM8M99",
    partida: "Santos - SP",
    destino: "Valinhos - SP",
  },
  {
    id: 70,
    responsavel: "Felipe Andrade",
    ordemDeTransporte: "OT-10070",
    status: "ocorrência",
    emissao: "2024-09-17 14:10:00.000Z",
    numerocontainer: "YMLU3355779",
    container: "Reefer 40'",
    notaFiscal: "103007",
    motorista: "Italo Ferreira",
    caminhao: "Mercedes-Benz Axor",
    placa: "QAZ3W44",
    partida: "Rio de Janeiro - RJ",
    destino: "Niterói - RJ",
  },
  {
    id: 71,
    responsavel: "Larissa Dias",
    ordemDeTransporte: "OT-10071",
    status: "trânsito",
    emissao: "2026-01-30 20:30:00.000Z",
    numerocontainer: "EVER8866442",
    container: "Dry 20'",
    notaFiscal: "103008",
    motorista: "Joaquim Cruz",
    caminhao: "DAF XF 480",
    placa: "EDC5R66",
    partida: "Pecém - CE",
    destino: "Maracanaú - CE",
  },
  {
    id: 72,
    responsavel: "Bruno Nogueira",
    ordemDeTransporte: "OT-10072",
    status: "coleta",
    emissao: "2025-02-24 10:00:00.000Z",
    numerocontainer: "ZIMU2244668",
    container: "Open Top",
    notaFiscal: "103009",
    motorista: "Klebber Toledo",
    caminhao: "Volkswagen Constellation",
    placa: "TGB7Y88",
    partida: "Manaus - AM",
    destino: "Manacapuru - AM",
  },
  {
    id: 73,
    responsavel: "Sofia Prado",
    ordemDeTransporte: "OT-10073",
    status: "entregue",
    emissao: "2024-04-03 16:50:00.000Z",
    numerocontainer: "UACU7755331",
    container: "Dry 40'",
    notaFiscal: "103010",
    motorista: "Luan Peres",
    caminhao: "Mercedes-Benz Atego",
    placa: "UJM9I00",
    partida: "Guarujá - SP",
    destino: "Guarulhos - SP",
  },
  {
    id: 74,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10074",
    status: "trânsito",
    emissao: "2026-06-25 12:40:00.000Z",
    numerocontainer: "KMTC9911223",
    container: "Reefer 20'",
    notaFiscal: "103011",
    motorista: "Mauricio Shogun",
    caminhao: "Volvo FM 380",
    placa: "OLP1Q22",
    partida: "Santos - SP",
    destino: "Osasco - SP",
  },
  {
    id: 75,
    responsavel: "Mariana Souza",
    ordemDeTransporte: "OT-10075",
    status: "coleta",
    emissao: "2025-07-16 05:20:00.000Z",
    numerocontainer: "WHLU4422119",
    container: "Flat Rack",
    notaFiscal: "103012",
    motorista: "Nelsinho Piquet",
    caminhao: "Scania R450",
    placa: "WSX3E44",
    partida: "Paranaguá - PR",
    destino: "Guarapuava - PR",
  },
  {
    id: 76,
    responsavel: "Lucas Ferreira",
    ordemDeTransporte: "OT-10076",
    status: "entregue",
    emissao: "2024-11-01 23:15:00.000Z",
    numerocontainer: "SITC6688002",
    container: "Dry 20'",
    notaFiscal: "103013",
    motorista: "Osmar Prado",
    caminhao: "MAN TGX 29.440",
    placa: "RFV5T66",
    partida: "Rio Grande - RS",
    destino: "Uruguaiana - RS",
  },
  {
    id: 77,
    responsavel: "Camila Rocha",
    ordemDeTransporte: "OT-10077",
    status: "ocorrência",
    emissao: "2026-03-18 18:05:00.000Z",
    numerocontainer: "TSLU1144770",
    container: "Dry 40'",
    notaFiscal: "103014",
    motorista: "Paulinho Gogó",
    caminhao: "Iveco Stralis",
    placa: "YHN7U88",
    partida: "Itajaí - SC",
    destino: "Tubarao - SC",
  },
  {
    id: 78,
    responsavel: "Rafael Barbosa",
    ordemDeTransporte: "OT-10078",
    status: "trânsito",
    emissao: "2025-05-29 03:30:00.000Z",
    numerocontainer: "SMLU3366992",
    container: "Reefer 40'",
    notaFiscal: "103015",
    motorista: "Rainer Cadete",
    caminhao: "Volvo FH 500",
    placa: "IK89O00",
    partida: "Suape - PE",
    destino: "Garanhuns - PE",
  },
  {
    id: 79,
    responsavel: "Beatriz Lima",
    ordemDeTransporte: "OT-10079",
    status: "coleta",
    emissao: "2024-08-14 09:10:00.000Z",
    numerocontainer: "IRSU5577003",
    container: "Open Top",
    notaFiscal: "103016",
    motorista: "Saulo Fernandes",
    caminhao: "Scania G450",
    placa: "QAZ1W22",
    partida: "Santos - SP",
    destino: "Americana - SP",
  },
  {
    id: 80,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10080",
    status: "entregue",
    emissao: "2026-04-02 15:00:00.000Z",
    numerocontainer: "MATS2255884",
    container: "Dry 40'",
    notaFiscal: "103017",
    motorista: "Tadeu Schmidt",
    caminhao: "DAF XF 530",
    placa: "EDC3R44",
    partida: "Vitoria - ES",
    destino: "Aracruz - ES",
  },
  {
    id: 81,
    responsavel: "Gabriel Santos",
    ordemDeTransporte: "OT-10081",
    status: "trânsito",
    emissao: "2025-12-10 21:40:00.000Z",
    numerocontainer: "TLLU8800224",
    container: "Dry 20'",
    notaFiscal: "103018",
    motorista: "Ulisses Correia",
    caminhao: "Volkswagen Meteor",
    placa: "TGB5Y66",
    partida: "Rio de Janeiro - RJ",
    destino: "Petrópolis - RJ",
  },
  {
    id: 82,
    responsavel: "Juliana Martins",
    ordemDeTransporte: "OT-10082",
    status: "coleta",
    emissao: "2024-02-17 07:25:00.000Z",
    numerocontainer: "HAMU4477115",
    container: "Reefer 20'",
    notaFiscal: "103019",
    motorista: "Vanderlei Luxemburgo",
    caminhao: "Mercedes-Benz Actros",
    placa: "UJM7I88",
    partida: "Salvador - BA",
    destino: "Alagoinhas - BA",
  },
  {
    id: 83,
    responsavel: "Thiago Oliveira",
    ordemDeTransporte: "OT-10083",
    status: "entregue",
    emissao: "2026-01-15 13:50:00.000Z",
    numerocontainer: "CULU1155996",
    container: "Flat Rack",
    notaFiscal: "103020",
    motorista: "Wilson Fittipaldi",
    caminhao: "Volvo FH 540",
    placa: "OLP9Q00",
    partida: "Santos - SP",
    destino: "Cotia - SP",
  },
  {
    id: 84,
    responsavel: "Fernanda Costa",
    ordemDeTransporte: "OT-10084",
    status: "ocorrência",
    emissao: "2025-06-03 10:30:00.000Z",
    numerocontainer: "CNIU7711448",
    container: "Dry 40'",
    notaFiscal: "103021",
    motorista: "Yago Mateus",
    caminhao: "Scania R540",
    placa: "WSX2E33",
    partida: "Pecém - CE",
    destino: "Iguatu - CE",
  },
  {
    id: 85,
    responsavel: "Patricia Mendes",
    ordemDeTransporte: "OT-10085",
    status: "trânsito",
    emissao: "2024-10-28 01:15:00.000Z",
    numerocontainer: "CSQU3399227",
    container: "Dry 20'",
    notaFiscal: "103022",
    motorista: "Zequinha de Abreu",
    caminhao: "MAN TGX 28.440",
    placa: "RFV4T55",
    partida: "Manaus - AM",
    destino: "Itacoatiara - AM",
  },
  {
    id: 86,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10086",
    status: "coleta",
    emissao: "2026-05-20 06:00:00.000Z",
    numerocontainer: "IALU6622883",
    container: "Reefer 40'",
    notaFiscal: "103023",
    motorista: "Arnaldo Cezar",
    caminhao: "Iveco Hi-Way",
    placa: "YHN6U77",
    partida: "Guarujá - SP",
    destino: "São José dos Campos - SP",
  },
  {
    id: 87,
    responsavel: "Rodrigo Alves",
    ordemDeTransporte: "OT-10087",
    status: "entregue",
    emissao: "2025-03-09 17:10:00.000Z",
    numerocontainer: "MOHU2288441",
    container: "Open Top",
    notaFiscal: "103024",
    motorista: "Beto Carrero",
    caminhao: "Volkswagen Constellation",
    placa: "IK80O11",
    partida: "Paranaguá - PR",
    destino: "Umuarama - PR",
  },
  {
    id: 88,
    responsavel: "Vanessa Cardoso",
    ordemDeTransporte: "OT-10088",
    status: "trânsito",
    emissao: "2024-07-12 11:45:00.000Z",
    numerocontainer: "SINU8844005",
    container: "Dry 40'",
    notaFiscal: "103025",
    motorista: "Chitãozinho Lima",
    caminhao: "Mercedes-Benz Atego",
    placa: "QAZ2W33",
    partida: "Rio Grande - RS",
    destino: "Bagé - RS",
  },
  {
    id: 89,
    responsavel: "Diego Ribeiro",
    ordemDeTransporte: "OT-10089",
    status: "coleta",
    emissao: "2026-02-04 04:20:00.000Z",
    numerocontainer: "SASU4400669",
    container: "Flat Rack",
    notaFiscal: "103026",
    motorista: "Denílson Show",
    caminhao: "Volvo FM 370",
    placa: "EDC4R55",
    partida: "Itajaí - SC",
    destino: "São José - SC",
  },
  {
    id: 90,
    responsavel: "Aline Carvalho",
    ordemDeTransporte: "OT-10090",
    status: "entregue",
    emissao: "2025-09-26 20:00:00.000Z",
    numerocontainer: "HEID1166224",
    container: "Dry 20'",
    notaFiscal: "103027",
    motorista: "Edilson Capetinha",
    caminhao: "Scania R450",
    placa: "TGB6Y77",
    partida: "Suape - PE",
    destino: "Cabo de Santo Agostinho - PE",
  },
  {
    id: 91,
    responsavel: "Marcelo Fonseca",
    ordemDeTransporte: "OT-10091",
    status: "ocorrência",
    emissao: "2024-01-31 08:30:00.000Z",
    numerocontainer: "GSLU7722998",
    container: "Reefer 40'",
    notaFiscal: "103028",
    motorista: "Flavio Canto",
    caminhao: "MAN TGX 29.480",
    placa: "UJM8I99",
    partida: "Santos - SP",
    destino: "Itapevi - SP",
  },
  {
    id: 92,
    responsavel: "Renata Vasconcelos",
    ordemDeTransporte: "OT-10092",
    status: "trânsito",
    emissao: "2026-04-15 14:15:00.000Z",
    numerocontainer: "CKLU3399553",
    container: "Dry 40'",
    notaFiscal: "103029",
    motorista: "Galvão Bueno",
    caminhao: "Volvo FH 460",
    placa: "OLP0Q11",
    partida: "Vitoria - ES",
    destino: "Guarapari - ES",
  },
  {
    id: 93,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10093",
    status: "coleta",
    emissao: "2025-08-21 23:50:00.000Z",
    numerocontainer: "NVIU9955117",
    container: "Open Top",
    notaFiscal: "103030",
    motorista: "Huguinho Silva",
    caminhao: "Scania G440",
    placa: "WSX4E55",
    partida: "Rio de Janeiro - RJ",
    destino: "Angra dos Reis - RJ",
  },
  {
    id: 94,
    responsavel: "Felipe Andrade",
    ordemDeTransporte: "OT-10094",
    status: "entregue",
    emissao: "2024-06-16 16:40:00.000Z",
    numerocontainer: "BENU5511882",
    container: "Dry 20'",
    notaFiscal: "103031",
    motorista: "Igor Kannário",
    caminhao: "DAF XF 480",
    placa: "RFV6T77",
    partida: "Salvador - BA",
    destino: "Lauro de Freitas - BA",
  },
  {
    id: 95,
    responsavel: "Larissa Dias",
    ordemDeTransporte: "OT-10095",
    status: "trânsito",
    emissao: "2026-03-24 02:10:00.000Z",
    numerocontainer: "LMCU2288006",
    container: "Reefer 20'",
    notaFiscal: "103032",
    motorista: "Juninho Pernambucano",
    caminhao: "Mercedes-Benz Actros",
    placa: "YHN8U99",
    partida: "Santos - SP",
    destino: "Taboão da Serra - SP",
  },
  {
    id: 96,
    responsavel: "Bruno Nogueira",
    ordemDeTransporte: "OT-10096",
    status: "coleta",
    emissao: "2025-11-03 09:25:00.000Z",
    numerocontainer: "DJLU8800441",
    container: "Flat Rack",
    notaFiscal: "103033",
    motorista: "Kaká Leite",
    caminhao: "Volkswagen Meteor",
    placa: "IK81O22",
    partida: "Pecém - CE",
    destino: "Caucaia - CE",
  },
  {
    id: 97,
    responsavel: "Sofia Prado",
    ordemDeTransporte: "OT-10097",
    status: "entregue",
    emissao: "2024-03-08 19:00:00.000Z",
    numerocontainer: "SWLU4444990",
    container: "Dry 40'",
    notaFiscal: "103034",
    motorista: "Léo Santana",
    caminhao: "Iveco Hi-Way",
    placa: "QAZ3W44",
    partida: "Manaus - AM",
    destino: "Parintins - AM",
  },
  {
    id: 98,
    responsavel: "Mariana Souza",
    ordemDeTransporte: "OT-10098",
    status: "ocorrência",
    emissao: "2026-01-02 12:35:00.000Z",
    numerocontainer: "PASU0099335",
    container: "Dry 20'",
    notaFiscal: "103035",
    motorista: "Milton Nascimento",
    caminhao: "Volvo FH 540",
    placa: "EDC5R66",
    partida: "Guarujá - SP",
    destino: "Suzano - SP",
  },
  {
    id: 99,
    responsavel: "Lucas Ferreira",
    ordemDeTransporte: "OT-10099",
    status: "trânsito",
    emissao: "2025-05-19 05:15:00.000Z",
    numerocontainer: "STXU6633881",
    container: "Reefer 40'",
    notaFiscal: "103036",
    motorista: "Naldo Benny",
    caminhao: "Scania R500",
    placa: "TGB7Y88",
    partida: "Paranaguá - PR",
    destino: "Toledo - PR",
  },
  {
    id: 100,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10100",
    status: "coleta",
    emissao: "2024-12-25 11:00:00.000Z",
    numerocontainer: "RONG1188226",
    container: "Open Top",
    notaFiscal: "103037",
    motorista: "Otávio Müller",
    caminhao: "DAF XF 530",
    placa: "UJM9I00",
    partida: "Rio Grande - RS",
    destino: "Pelotas - RS",
  },
  {
    id: 101,
    responsavel: "Camila Rocha",
    ordemDeTransporte: "OT-10101",
    status: "entregue",
    emissao: "2026-06-11 17:30:00.000Z",
    numerocontainer: "TRHU7722004",
    container: "Dry 40'",
    notaFiscal: "103038",
    motorista: "Pepeu Gomes",
    caminhao: "MAN TGX 28.440",
    placa: "OLP1Q22",
    partida: "Itajaí - SC",
    destino: "Palhoça - SC",
  },
  {
    id: 102,
    responsavel: "Rafael Barbosa",
    ordemDeTransporte: "OT-10102",
    status: "trânsito",
    emissao: "2025-02-13 22:20:00.000Z",
    numerocontainer: "TGHU3300559",
    container: "Dry 20'",
    notaFiscal: "103039",
    motorista: "Quim Barreiros",
    caminhao: "Mercedes-Benz Atego",
    placa: "WSX3E44",
    partida: "Suape - PE",
    destino: "Olinda - PE",
  },
  {
    id: 103,
    responsavel: "Beatriz Lima",
    ordemDeTransporte: "OT-10103",
    status: "coleta",
    emissao: "2024-09-07 08:05:00.000Z",
    numerocontainer: "MBLU9944113",
    container: "Reefer 20'",
    notaFiscal: "103040",
    motorista: "Reginaldo Rossi",
    caminhao: "Volvo FM 380",
    placa: "RFV5T66",
    partida: "Santos - SP",
    destino: "Diadema - SP",
  },
  {
    id: 104,
    responsavel: "Gabriel Santos",
    ordemDeTransporte: "OT-10104",
    status: "entregue",
    emissao: "2026-03-31 13:40:00.000Z",
    numerocontainer: "BLJU5588668",
    container: "Flat Rack",
    notaFiscal: "103041",
    motorista: "Seu Jorge",
    caminhao: "Scania R450",
    placa: "YHN7U88",
    partida: "Vitoria - ES",
    destino: "Linhares - ES",
  },
  {
    id: 105,
    responsavel: "Juliana Martins",
    ordemDeTransporte: "OT-10105",
    status: "ocorrência",
    emissao: "2025-07-27 20:15:00.000Z",
    numerocontainer: "SNCU1111772",
    container: "Dry 40'",
    notaFiscal: "103042",
    motorista: "Toni Garrido",
    caminhao: "Volkswagen Constellation",
    placa: "IK89O00",
    partida: "Rio de Janeiro - RJ",
    destino: "Nova Iguaçu - RJ",
  },
  {
    id: 106,
    responsavel: "Thiago Oliveira",
    ordemDeTransporte: "OT-10106",
    status: "trânsito",
    emissao: "2024-04-19 03:55:00.000Z",
    numerocontainer: "GESU7766221",
    container: "Dry 20'",
    notaFiscal: "103043",
    motorista: "Ubiratan Guimarães",
    caminhao: "Mercedes-Benz Actros",
    placa: "QAZ1W22",
    partida: "Salvador - BA",
    destino: "Simões Filho - BA",
  },
  {
    id: 107,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10107",
    status: "coleta",
    emissao: "2026-02-22 10:10:00.000Z",
    numerocontainer: "VMCU3322886",
    container: "Reefer 40'",
    notaFiscal: "103044",
    motorista: "Vitor Kley",
    caminhao: "Volvo FH 500",
    placa: "EDC3R44",
    partida: "Santos - SP",
    destino: "Carapicuíba - SP",
  },
  {
    id: 108,
    responsavel: "Fernanda Costa",
    ordemDeTransporte: "OT-10108",
    status: "entregue",
    emissao: "2025-10-10 15:25:00.000Z",
    numerocontainer: "LCLU8877330",
    container: "Open Top",
    notaFiscal: "103045",
    motorista: "Welson Tremendão",
    caminhao: "DAF XF 480",
    placa: "TGB5Y66",
    partida: "Pecém - CE",
    destino: "Sobral - CE",
  },
  {
    id: 109,
    responsavel: "Patricia Mendes",
    ordemDeTransporte: "OT-10109",
    status: "trânsito",
    emissao: "2024-08-30 21:00:00.000Z",
    numerocontainer: "HDAS2233994",
    container: "Dry 40'",
    notaFiscal: "103046",
    motorista: "Xande de Pilares",
    caminhao: "MAN TGX 29.480",
    placa: "UJM7I88",
    partida: "Manaus - AM",
    destino: "Coari - AM",
  },
  {
    id: 110,
    responsavel: "Rodrigo Alves",
    ordemDeTransporte: "OT-10110",
    status: "coleta",
    emissao: "2026-05-08 07:45:00.000Z",
    numerocontainer: "KASD6699118",
    container: "Dry 20'",
    notaFiscal: "103047",
    motorista: "Yassir Chediak",
    caminhao: "Iveco Hi-Way",
    placa: "OLP9Q00",
    partida: "Guarujá - SP",
    destino: "Itaquaquecetuba - SP",
  },
  {
    id: 111,
    responsavel: "Vanessa Cardoso",
    ordemDeTransporte: "OT-10111",
    status: "entregue",
    emissao: "2025-01-05 12:50:00.000Z",
    numerocontainer: "POIS1144552",
    container: "Reefer 20'",
    notaFiscal: "103048",
    motorista: "Zé Ramalho",
    caminhao: "Volkswagen Meteor",
    placa: "WSX2E33",
    partida: "Paranaguá - PR",
    destino: "Arapongas - PR",
  },
  {
    id: 112,
    responsavel: "Diego Ribeiro",
    ordemDeTransporte: "OT-10112",
    status: "ocorrência",
    emissao: "2024-11-18 18:35:00.000Z",
    numerocontainer: "LKJS7700887",
    container: "Flat Rack",
    notaFiscal: "103049",
    motorista: "Amaury Junior",
    caminhao: "Scania G450",
    placa: "RFV4T55",
    partida: "Rio Grande - RS",
    destino: "Canoas - RS",
  },
  {
    id: 113,
    responsavel: "Aline Carvalho",
    ordemDeTransporte: "OT-10113",
    status: "trânsito",
    emissao: "2026-04-20 01:20:00.000Z",
    numerocontainer: "MNBV3355221",
    container: "Dry 40'",
    notaFiscal: "103050",
    motorista: "Beto Barbosa",
    caminhao: "Volvo FH 540",
    placa: "YHN6U77",
    partida: "Itajaí - SC",
    destino: "Itapema - SC",
  },
  {
    id: 114,
    responsavel: "Eduardo Nascimento",
    ordemDeTransporte: "OT-10114",
    status: "coleta",
    emissao: "2025-06-28 09:00:00.000Z",
    numerocontainer: "CXZA8811666",
    container: "Open Top",
    notaFiscal: "103051",
    motorista: "Chico César",
    caminhao: "Mercedes-Benz Atego",
    placa: "IK80O11",
    partida: "Suape - PE",
    destino: "Paulista - PE",
  },
  {
    id: 115,
    responsavel: "Marcelo Fonseca",
    ordemDeTransporte: "OT-10115",
    status: "entregue",
    emissao: "2024-02-09 14:40:00.000Z",
    numerocontainer: "QWYE2266000",
    container: "Dry 20'",
    notaFiscal: "103052",
    motorista: "Dudu Nobre",
    caminhao: "Volvo FM 370",
    placa: "QAZ2W33",
    partida: "Santos - SP",
    destino: "Mauá - SP",
  },
  {
    id: 116,
    responsavel: "Renata Vasconcelos",
    ordemDeTransporte: "OT-10116",
    status: "trânsito",
    emissao: "2026-01-18 20:05:00.000Z",
    numerocontainer: "IUYT6600445",
    container: "Reefer 40'",
    notaFiscal: "103053",
    motorista: "Eri Johnson",
    caminhao: "Scania R540",
    placa: "EDC4R55",
    partida: "Vitoria - ES",
    destino: "São Mateus - ES",
  },
  {
    id: 117,
    responsavel: "Felipe Andrade",
    ordemDeTransporte: "OT-10117",
    status: "coleta",
    emissao: "2025-12-14 06:15:00.000Z",
    numerocontainer: "OIKJ0044889",
    container: "Flat Rack",
    notaFiscal: "103054",
    motorista: "Frank Aguiar",
    caminhao: "DAF XF 530",
    placa: "TGB6Y77",
    partida: "Rio de Janeiro - RJ",
    destino: "Cabo Frio - RJ",
  },
  {
    id: 118,
    responsavel: "Larissa Dias",
    ordemDeTransporte: "OT-10118",
    status: "entregue",
    emissao: "2024-10-01 11:30:00.000Z",
    numerocontainer: "YTRE5599333",
    container: "Dry 40'",
    notaFiscal: "103055",
    motorista: "Gilliard Cordeiro",
    caminhao: "MAN TGX 28.440",
    placa: "UJM8I99",
    partida: "Salvador - BA",
    destino: "Candeias - BA",
  },
  {
    id: 119,
    responsavel: "Bruno Nogueira",
    ordemDeTransporte: "OT-10119",
    status: "ocorrência",
    emissao: "2026-03-08 16:50:00.000Z",
    numerocontainer: "RTEW1133777",
    container: "Dry 20'",
    notaFiscal: "103056",
    motorista: "Humberto Gessinger",
    caminhao: "Iveco Stralis",
    placa: "OLP0Q11",
    partida: "Santos - SP",
    destino: "Embu das Artes - SP",
  },
  {
    id: 120,
    responsavel: "Sofia Prado",
    ordemDeTransporte: "OT-10120",
    status: "trânsito",
    emissao: "2025-04-25 23:10:00.000Z",
    numerocontainer: "FDA20022448",
    container: "Reefer 20'",
    notaFiscal: "103057",
    motorista: "Ivan Lins",
    caminhao: "Volkswagen Meteor",
    placa: "WSX4E55",
    partida: "Pecém - CE",
    destino: "Crato - CE",
  },
];

  const items = [
    { label: "Todos os Status", value: "todos" },
    { label: "Trânsito", value: "trânsito" },
    { label: "Entregue", value: "entregue" },
    { label: "Coleta", value: "coleta" },
    { label: "Ocorrência", value: "ocorrência" },
  ];

  const filteredOrders = ordemDeTransporte.filter((item) => {
    const term = searchTerm.toLowerCase();

    const matchesSearch =
      item.ordemDeTransporte.toLowerCase().includes(term) ||
      item.motorista.toLowerCase().includes(term) ||
      item.numerocontainer.toLowerCase().includes(term) ||
      item.placa.toLowerCase().includes(term) ||
      item.notaFiscal.toLowerCase().includes(term) ||
      item.status.toLowerCase().includes(term) ||
      item.responsavel.toLowerCase().includes(term);

    const matchesStatus =
      selectedStatus === "todos" ||
      item.status.toLowerCase() === selectedStatus.toLowerCase();

    return matchesSearch && matchesStatus;
  });

  return (
    <div className="container mx-auto p-4 md:p-6 space-y-6 max-w-7xl">
      {/* Header & Ações */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b pb-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <Truck className="h-7 w-7 text-primary" />
            Ordens de Transporte
          </h1>
          <p className="text-sm text-muted-foreground">
            Gerencie o fluxo e status dos fretes operacionais.
          </p>
        </div>

        <Button className="w-full sm:w-auto shadow-sm transition-all hover:shadow-md cursor-pointer">
          <Plus className="mr-2 h-4 w-4" />
          Nova Ordem
        </Button>
      </div>

      {/* Barra de Pesquisa e Filtros */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 bg-card p-4 rounded-xl border shadow-sm">
        <div className="flex justify-start items-center w-full gap-2">
          <div className="relative w-full sm:max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Buscar por OT, motorista, container, placa..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 bg-background"
            />
          </div>

          <Field className="w-50">
            <Select value={selectedStatus} onValueChange={setSelectedStatus}>
              <SelectTrigger>
                <SelectValue placeholder="Selecione o Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {items.map((item) => (
                    <SelectItem className="cursor-pointer" key={item.value} value={item.value}>
                      {item.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </Field>
        </div>
        <div className="text-xs text-muted-foreground self-end sm:self-center font-medium shrink-0">
          Exibindo {filteredOrders.length} de {ordemDeTransporte.length}{" "}
          registros
        </div>
      </div>

      {/* Lista de Cards */}
      {filteredOrders.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredOrders.map((item) => (
            <CardOrdemTransporte
              key={item.id}
              ordemDeTransporte={item.ordemDeTransporte}
              responsavel={item.responsavel}
              status={item.status}
              emissao={item.emissao}
              numerocontainer={item.numerocontainer}
              notaFiscal={item.notaFiscal}
              container={item.container}
              motorista={item.motorista}
              placa={item.placa}
              caminhao={item.caminhao}
              partida={item.partida}
              destino={item.destino}
            />
          ))}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center p-12 text-center rounded-xl border border-dashed">
          <p className="text-muted-foreground font-medium">
            Nenhuma ordem de transporte encontrada.
          </p>
        </div>
      )}
    </div>
  );
}