/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CreateAccountIndexRouteImport } from './routes/create-account/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CreateAccountFormAccountRouteImport } from './routes/create-account/formAccount'
import { Route as CreateAccountCredentialsRouteImport } from './routes/create-account/credentials'
import { Route as CreateAccountConfirmedEmailRouteImport } from './routes/create-account/confirmed-email'
import { Route as AuthenticatedOrdemDeTransporteRouteImport } from './routes/_authenticated/ordemDeTransporte'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountIndexRoute = CreateAccountIndexRouteImport.update({
  id: '/create-account/',
  path: '/create-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CreateAccountFormAccountRoute =
  CreateAccountFormAccountRouteImport.update({
    id: '/create-account/formAccount',
    path: '/create-account/formAccount',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateAccountCredentialsRoute =
  CreateAccountCredentialsRouteImport.update({
    id: '/create-account/credentials',
    path: '/create-account/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateAccountConfirmedEmailRoute =
  CreateAccountConfirmedEmailRouteImport.update({
    id: '/create-account/confirmed-email',
    path: '/create-account/confirmed-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrdemDeTransporteRoute =
  AuthenticatedOrdemDeTransporteRouteImport.update({
    id: '/ordemDeTransporte',
    path: '/ordemDeTransporte',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ordemDeTransporte': typeof AuthenticatedOrdemDeTransporteRoute
  '/create-account/confirmed-email': typeof CreateAccountConfirmedEmailRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formAccount': typeof CreateAccountFormAccountRoute
  '/create-account/': typeof CreateAccountIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ordemDeTransporte': typeof AuthenticatedOrdemDeTransporteRoute
  '/create-account/confirmed-email': typeof CreateAccountConfirmedEmailRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formAccount': typeof CreateAccountFormAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/create-account': typeof CreateAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ordemDeTransporte': typeof AuthenticatedOrdemDeTransporteRoute
  '/create-account/confirmed-email': typeof CreateAccountConfirmedEmailRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formAccount': typeof CreateAccountFormAccountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/create-account/': typeof CreateAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/ordemDeTransporte'
    | '/create-account/confirmed-email'
    | '/create-account/credentials'
    | '/create-account/formAccount'
    | '/create-account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/ordemDeTransporte'
    | '/create-account/confirmed-email'
    | '/create-account/credentials'
    | '/create-account/formAccount'
    | '/'
    | '/create-account'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/ordemDeTransporte'
    | '/create-account/confirmed-email'
    | '/create-account/credentials'
    | '/create-account/formAccount'
    | '/_authenticated/'
    | '/create-account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CreateAccountConfirmedEmailRoute: typeof CreateAccountConfirmedEmailRoute
  CreateAccountCredentialsRoute: typeof CreateAccountCredentialsRoute
  CreateAccountFormAccountRoute: typeof CreateAccountFormAccountRoute
  CreateAccountIndexRoute: typeof CreateAccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account/': {
      id: '/create-account/'
      path: '/create-account'
      fullPath: '/create-account/'
      preLoaderRoute: typeof CreateAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/create-account/formAccount': {
      id: '/create-account/formAccount'
      path: '/create-account/formAccount'
      fullPath: '/create-account/formAccount'
      preLoaderRoute: typeof CreateAccountFormAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account/credentials': {
      id: '/create-account/credentials'
      path: '/create-account/credentials'
      fullPath: '/create-account/credentials'
      preLoaderRoute: typeof CreateAccountCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account/confirmed-email': {
      id: '/create-account/confirmed-email'
      path: '/create-account/confirmed-email'
      fullPath: '/create-account/confirmed-email'
      preLoaderRoute: typeof CreateAccountConfirmedEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ordemDeTransporte': {
      id: '/_authenticated/ordemDeTransporte'
      path: '/ordemDeTransporte'
      fullPath: '/ordemDeTransporte'
      preLoaderRoute: typeof AuthenticatedOrdemDeTransporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOrdemDeTransporteRoute: typeof AuthenticatedOrdemDeTransporteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOrdemDeTransporteRoute: AuthenticatedOrdemDeTransporteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  CreateAccountConfirmedEmailRoute: CreateAccountConfirmedEmailRoute,
  CreateAccountCredentialsRoute: CreateAccountCredentialsRoute,
  CreateAccountFormAccountRoute: CreateAccountFormAccountRoute,
  CreateAccountIndexRoute: CreateAccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
