/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CreateAccountIndexRouteImport } from './routes/create-account/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CreateAccountFormCreateAccountCredentialsRouteImport } from './routes/create-account/formCreateAccountCredentials'
import { Route as CreateAccountCredentialsRouteImport } from './routes/create-account/credentials'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountIndexRoute = CreateAccountIndexRouteImport.update({
  id: '/create-account/',
  path: '/create-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CreateAccountFormCreateAccountCredentialsRoute =
  CreateAccountFormCreateAccountCredentialsRouteImport.update({
    id: '/create-account/formCreateAccountCredentials',
    path: '/create-account/formCreateAccountCredentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateAccountCredentialsRoute =
  CreateAccountCredentialsRouteImport.update({
    id: '/create-account/credentials',
    path: '/create-account/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formCreateAccountCredentials': typeof CreateAccountFormCreateAccountCredentialsRoute
  '/create-account/': typeof CreateAccountIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formCreateAccountCredentials': typeof CreateAccountFormCreateAccountCredentialsRoute
  '/': typeof AuthenticatedIndexRoute
  '/create-account': typeof CreateAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/create-account/credentials': typeof CreateAccountCredentialsRoute
  '/create-account/formCreateAccountCredentials': typeof CreateAccountFormCreateAccountCredentialsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/create-account/': typeof CreateAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/create-account/credentials'
    | '/create-account/formCreateAccountCredentials'
    | '/create-account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create-account/credentials'
    | '/create-account/formCreateAccountCredentials'
    | '/'
    | '/create-account'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/create-account/credentials'
    | '/create-account/formCreateAccountCredentials'
    | '/_authenticated/'
    | '/create-account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CreateAccountCredentialsRoute: typeof CreateAccountCredentialsRoute
  CreateAccountFormCreateAccountCredentialsRoute: typeof CreateAccountFormCreateAccountCredentialsRoute
  CreateAccountIndexRoute: typeof CreateAccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account/': {
      id: '/create-account/'
      path: '/create-account'
      fullPath: '/create-account/'
      preLoaderRoute: typeof CreateAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/create-account/formCreateAccountCredentials': {
      id: '/create-account/formCreateAccountCredentials'
      path: '/create-account/formCreateAccountCredentials'
      fullPath: '/create-account/formCreateAccountCredentials'
      preLoaderRoute: typeof CreateAccountFormCreateAccountCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account/credentials': {
      id: '/create-account/credentials'
      path: '/create-account/credentials'
      fullPath: '/create-account/credentials'
      preLoaderRoute: typeof CreateAccountCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  CreateAccountCredentialsRoute: CreateAccountCredentialsRoute,
  CreateAccountFormCreateAccountCredentialsRoute:
    CreateAccountFormCreateAccountCredentialsRoute,
  CreateAccountIndexRoute: CreateAccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
